/* Mirrors the site's Google Fonts into assets/fonts/, so the pages can stop
   asking two other hosts for their type. Fetches the same css2 URLs the pages
   used to link, with a Chrome UA so Google answers in variable woff2, then
   downloads every file the CSS names and rewrites the urls to point beside
   this copy. Every unicode-range subset is kept, so nothing a visitor could
   render today goes missing tomorrow.

   Re-run it to pick up new font versions: `node scripts/fonts-vendor.mjs`.
   It overwrites assets/fonts/fonts.css and assets/fonts/files/. */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'assets', 'fonts');
const filesDir = join(outDir, 'files');

/* A UA Google recognises as modern, so the CSS comes back as variable woff2
   with unicode-range subsets rather than as TTFs for a museum piece. */
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

/* The same requests the pages made, verbatim — including the Long Cang one,
   which is subset to the three characters of the name and nothing else. */
const SHEETS = [
    'https://fonts.googleapis.com/css2?family=Azeret+Mono:ital,wght@0,100..900;1,100..900&family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Philosopher:ital,wght@0,400;0,700;1,400;1,700&display=swap',
    'https://fonts.googleapis.com/css2?family=Long+Cang&text=%E6%9D%A8%E6%B3%93%E9%94%B4&display=swap',
];

await mkdir(filesDir, { recursive: true });

const seen = new Map(); // remote url -> local basename
let css = `/* Generated by scripts/fonts-vendor.mjs — do not edit by hand. */\n`;

for (const sheet of SHEETS) {
    const res = await fetch(sheet, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${res.status} for ${sheet}`);
    let text = await res.text();

    for (const url of new Set(text.match(/https:\/\/fonts\.gstatic\.com\/[^)]+/g))) {
        if (!seen.has(url)) {
            /* Google's path already names the family and holds a version+hash
               (…/ebgaramond/v31/SlGDmQSN….woff2); folding it to family-hash
               keeps the name unique, readable, and stable across re-runs. */
            const parts = new URL(url).pathname.split('/').filter(Boolean);
            const family = parts[1];
            const base = parts[parts.length - 1];
            seen.set(url, `${family}-${base}`);
            const file = await fetch(url, { headers: { 'User-Agent': UA } });
            if (!file.ok) throw new Error(`${file.status} for ${url}`);
            await writeFile(join(filesDir, seen.get(url)), Buffer.from(await file.arrayBuffer()));
        }
        text = text.replaceAll(url, `files/${seen.get(url)}`);
    }
    css += '\n' + text.trim() + '\n';
}

await writeFile(join(outDir, 'fonts.css'), css);
console.log(`wrote fonts.css + ${seen.size} files to assets/fonts/`);
